[[main]]
  name = "Our Work"
  pageRef = "/our-work"
  weight = 10

[[main]]
  name = "The Framework"
  pageRef = "/the-framework"
  weight = 20

[[main]]
  name = "Publications"
  identifier = "publications"
  pageRef = "/publications"
  weight = 30

[[main]]
  name = "Academic Papers"
  parent = "publications"
  pageRef = "/publications/academic-papers"
  weight = 1

[[main]]
  name = "Op-Eds"
  parent = "publications"
  pageRef = "/publications/op-eds"
  weight = 2

[[main]]
  name = "Policy Briefs"
  parent = "publications"
  pageRef = "/publications/policy-briefs"
  weight = 3

[[main]]
  name = "Resources"
  identifier = "resources"
  pageRef = "/resources"
  weight = 40

[[main]]
  name = "MOOC"
  parent = "resources"
  pageRef = "/resources/mooc"
  weight = 1

[[main]]
  name = "Podcast"
  parent = "resources"
  pageRef = "/resources/podcast"
  weight = 2

[[main]]
  name = "Advocacy Toolkit"
  parent = "resources"
  pageRef = "/resources/advocacy-toolkit"
  weight = 3

[[main]]
  name = "The Book Projects"
  parent = "resources"
  pageRef = "/resources/the-book"
  weight = 4

[[main]]
  name = "Contact Us"
  pageRef = "/contact-us"
  weight = 50